// docs/view/advance/jsx/todo-table.jsx
/* eslint-env es6 */
import React from 'react';

class TodoTable extends React.Component {
    constructor( props ) {
        super( props );
    }

    render() {
        return (
            <table>
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {
                    this.props.items.map( ( item, idx ) =>
                        <tr key={idx}>
                          <td>{item.item_desc}</td>
                          <td>{item.item_status}</td>
                        </tr>
                    )
                }
              </tbody>
            </table>
        );
    }
}
export default TodoTable;

// docs/view/advance/vue/todo-table.vue
<template>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item of items" v-bind:key="item.id">
          <td>{{item.item_desc}}</td>
          <td>{{item.item_status}}</td>
        </tr>
      </tbody>
    </table>
</template>

<script>
module.exports = {
    props: ['items'],
}
</script>
